### ISSUE TITLE
Outgoing Message Error

### ISSUE THREAD

**Issue by widmr** [CamHenlin/iMessageWebClient#2]
Hi,
I get the following error while trying to send a message via the web interface:

```
mbp ~/iMessage $ PORT=1337 npm start

> imessagewebclient@1.0.0 start /Users/andreas/iMessage
> node app.js

_http_outgoing.js:512
    throw new TypeError('first argument must be a string or Buffer');
          ^
TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:512:11)
    at writeend (/Users/andreas/iMessage/node_modules/express-session/index.js:219:22)
    at Immediate.ontouch [as _onImmediate] (/Users/andreas/iMessage/node_modules/express-session/index.js:303:11)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! imessagewebclient@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the imessagewebclient@1.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the imessagewebclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls imessagewebclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andreas/iMessage/npm-debug.log
```

**Comment by CamHenlin** [comment]
Hi, widmr, thanks for your report. You didn't happen to notice a failure at the npm install step did you? I just want to try to reproduce your problem and it looks like one of the npm modules is broken now, and the app only sort of works after the install fails. I'll troubleshoot in a little bit and try to push an update this afternoon

**Comment by widmr** [comment]
Thanks for your reply.
There was no error while installing die npm package.

**Comment by CamHenlin** [comment]
Finally had a chance to get this fixed up. Give the latest version a shot and let me know if you have any more issues.
