### ISSUE TITLE
Error During Starting...

### ISSUE THREAD

**Issue by masterdoctor** [CamHenlin/iMessageWebClient#6]
```bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Object.<anonymous> (/Users/mearns/imessagewebclient/app.js:395:48)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! imessagewebclient@1.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the imessagewebclient@1.0.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the imessagewebclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls imessagewebclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mearns/imessagewebclient/npm-debug.log
```

**Comment by masterdoctor** [comment]
I get this whenever I try to start the web app. I am unable to locate events.js

**Comment by masterdoctor** [comment]
OK, fixed that error, the problem now is that when I try and connect it says server unexpectedly dropped the connection.

**Comment by masterdoctor** [comment]
OK, For what it's worth I managed to fix this issue by opening the server on Port 444,
